### ISSUE TITLE
ps can't get full commond args for tail

### ISSUE THREAD

**Issue by hanxi** [zsoltf/tmux-save-sessions#4]
Like `tail -100f app.log`. 
`ps -o 'args=' -p $child` whill get `tail -100` in mac OSX. the `f app.log` be cut.

**Comment by zsoltf** [comment]
@hanxi, thanks for your feedback!
while I was testing this, I noticed that running `tail -100f file.log` cuts off the `f file.log` part even when running `ps aux | grep tail`.
If you separate the arguments, `ps` parses them correctly. This should work:`tail -100 -f app.log`
